# Generated by Django 6.0.1 on 2026-02-01 10:04

import coverse_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=coverse_app.models.upload_to, verbose_name='Обложка')),
                ('privacy', models.CharField(choices=[('public', 'Публичный'), ('unlisted', 'По ссылке'), ('private', 'Только я')], default='public', max_length=20, verbose_name='Доступность')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В разработке'), ('completed', 'Завершён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='coverse_app.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок раздела')),
                ('section_type', models.CharField(choices=[('plot', 'Сюжет'), ('world', 'Мир'), ('characters', 'Персонажи'), ('concepts', 'Концепты'), ('art', 'Искусство'), ('other', 'Прочее')], max_length=20, verbose_name='Тип раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='coverse_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order'],
                'unique_together': {('project', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='coverse_app.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_excerpt', models.TextField(blank=True, verbose_name='Цитата из поста (для контекста)')),
                ('suggestion_text', models.TextField(verbose_name='Предложение')),
                ('visibility', models.CharField(choices=[('author_only', 'Только автору'), ('public', 'Публичное')], default='public', max_length=20, verbose_name='Видимость')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('reviewed', 'Рассмотрено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_made', to=settings.AUTH_USER_MODEL, verbose_name='Автор предложения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='coverse_app.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(choices=[('suggestion_accepted', 'Принятое предложение'), ('co_author', 'Соавторство'), ('artwork', 'Иллюстрация'), ('editing', 'Редактура')], max_length=30, verbose_name='Тип вклада')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание вклада')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='coverse_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
                'unique_together': {('project', 'contributor', 'credit_type', 'description')},
            },
        ),
    ]
