# Generated by Django 6.0.1 on 2026-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
    ]
