# Generated by Django 4.2.27 on 2026-02-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverse_app', '0003_alter_contributioncredit_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён (скрыт)'),
        ),
    ]
