# Generated by Django 4.2.27 on 2026-02-03 02:33

import coverse_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverse_app', '0004_post_deleted_at_post_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=coverse_app.models.post_image_upload_to, verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись (опционально)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coverse_app.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Изображение к посту',
                'verbose_name_plural': 'Изображения к посту',
                'ordering': ['order', 'id'],
            },
        ),
    ]
