# Generated by Django 4.2.27 on 2026-02-03 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coverse_app', '0005_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderation_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён модерацией'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления модерацией'),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Скрыт модерацией'),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_status',
            field=models.CharField(choices=[('active', 'Активен'), ('hidden_by_moderation', 'Скрыт модерацией')], default='active', max_length=30, verbose_name='Статус модерации'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
