# Generated by Django 6.0.1 on 2026-03-03 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverse_app', '0009_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано автором'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('correction', 'Исправление'), ('new_idea', 'Новая идея'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип предложения'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено'),
        ),
        migrations.CreateModel(
            name='PostEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField(editable=False, verbose_name='Старое содержание')),
                ('new_content', models.TextField(editable=False, verbose_name='Новое содержание')),
                ('old_title', models.CharField(editable=False, max_length=200, verbose_name='Старый заголовок')),
                ('new_title', models.CharField(editable=False, max_length=200, verbose_name='Новый заголовок')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('change_summary', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_edits', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='coverse_app.post', verbose_name='Пост')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_edit_logs', to='coverse_app.suggestion', verbose_name='Предложение (инициатор)')),
            ],
            options={
                'verbose_name': 'Лог изменения поста',
                'verbose_name_plural': 'Логи изменений постов',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddField(
            model_name='suggestion',
            name='accepted_post_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_suggestions', to='coverse_app.posteditlog', verbose_name='Версия поста после принятия'),
        ),
        migrations.CreateModel(
            name='SuggestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='suggestions/', verbose_name='Файл')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='coverse_app.suggestion', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Вложение к предложению',
                'verbose_name_plural': 'Вложения к предложениям',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
