# Generated by Django 6.0.1 on 2026-03-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverse_app', '0010_suggestion_read_at_suggestion_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Удаляем старую процедуру (если есть)
            DROP PROCEDURE IF EXISTS proc_get_admin_statistics();

            -- Создаём функцию для статистики
            CREATE OR REPLACE FUNCTION fn_get_admin_statistics()
            RETURNS TABLE (
                total_users INTEGER,
                total_projects INTEGER,
                public_projects INTEGER,
                total_suggestions INTEGER,
                new_suggestions INTEGER
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RETURN QUERY
                SELECT 
                    (SELECT COUNT(*) FROM auth_user)::INTEGER,
                    (SELECT COUNT(*) FROM coverse_app_project)::INTEGER,
                    (SELECT COUNT(*) FROM coverse_app_project WHERE privacy = 'public')::INTEGER,
                    (SELECT COUNT(*) FROM coverse_app_suggestion)::INTEGER,
                    (SELECT COUNT(*) FROM coverse_app_suggestion WHERE status = 'new')::INTEGER;
            END;
            $$;
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS fn_get_admin_statistics();
            """
        ),
    ]